name: Run Cypress Client Tests

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-node
    - run: sudo apt-get install -y redis-tools redis-server
      shell: bash
    - run: redis-cli ping
      shell: bash
    - run: |
        cd client
        pnpm add -g concurrently wait-on
        pnpm cypress install
        pnpm concurrently --kill-others --success first "pnpm --prefix ../server dev" "pnpm start:cypress" "pnpm wait-on tcp:8008 && pnpm wait-on http://localhost:3000 && pnpm cypress run"
      shell: bash
    - name: Save Cypress Output
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: cypress-output
        path: |
          **/cypress/screenshots/
          **/cypress/videos/
        retention-days: 7
