name: Setup Node

runs:
  using: composite
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      with:
        version: 11
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 24.x
        cache: pnpm
        cache-dependency-path: server/pnpm-lock.yaml
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 24.x
        cache: pnpm
        cache-dependency-path: client/pnpm-lock.yaml
    - run: |
        pnpm i -g vercel
        cd server
        pnpm i
        cd ../client
        pnpm i
      shell: bash
