name: Setup Node

runs:
  using: composite
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        version: 9
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 20.x
        cache: pnpm
        cache-dependency-path: server/pnpm-lock.yaml
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 20.x
        cache: pnpm
        cache-dependency-path: client/pnpm-lock.yaml
    - run: |
        pnpm i -g vercel
        cd server
        pnpm i
        cd ../client
        pnpm i
      shell: bash
