name: Setup Node

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: pnpm/action-setup@v4
    with:
      version: 9
  - uses: actions/setup-node@v4
    with:
      node-version: 20.x
      cache: pnpm
      cache-dependency-path: server/pnpm-lock.yaml
  - uses: actions/setup-node@v4
    with:
      node-version: 20.x
      cache: pnpm
      cache-dependency-path: client/pnpm-lock.yaml
  - run: |
      cd server
      pnpm i
      cd ../client
      pnpm i
    shell: bash
