version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/shared"
      - "/server"
      - "/client"
    schedule:
      interval: "weekly"
    groups:
      nonMajor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
