version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/shared"
      - "/server"
      - "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
