name: Run Lint

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: ./.github/actions/setup-node
  - run: |
      cd server
      pnpm lint
    shell: bash
  - run: |
      cd client
      pnpm lint
    shell: bash
