name: Run Lint

runs:
  using: composite
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: ./.github/actions/setup-node
    - run: |
        cd server
        pnpm lint
      shell: bash
    - run: |
        cd client
        pnpm lint
      shell: bash
