name: Run Vitest Client Tests

runs:
  using: composite
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: ./.github/actions/setup-node
    - run: |
        cd client
        pnpm test
      shell: bash
