name: Run Vitest Client Tests

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-node
    - run: |
        cd client
        pnpm test
      shell: bash
