name: Run Vitest Client Tests

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Node and dependencies
      uses: ./.github/actions/setup-node
    - name: Run client typecheck and vitest
      run: |
        cd client
        pnpm typecheck
        pnpm test
      shell: bash
