name: Check Package Size

inputs:
  npm-token:
    description: NPM Token
    required: true

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: ./.github/actions/setup-node
    with:
      npm-token: ${{ inputs.npm-token }}
  - name: Define Bundle Size Limit
    run: |
      BUNDLE_SIZE_LIMIT_BYTES=2800000
      echo "BUNDLE_SIZE_LIMIT_BYTES=$BUNDLE_SIZE_LIMIT_BYTES" >> $GITHUB_ENV
    shell: bash
  - name: Get Bundle Size
    run: |
      BUNDLE_SIZE_BYTES=$(pnpm --silent package-bundle-size)
      echo "$BUNDLE_SIZE_BYTES"
      if [ -z "$BUNDLE_SIZE_BYTES" ]
      then
        exit 1
      fi
      echo "BUNDLE_SIZE_BYTES=$BUNDLE_SIZE_BYTES" >> $GITHUB_ENV
    shell: bash
  - name: Enforce Bundle Size Limit
    run: |
      if (( $BUNDLE_SIZE_BYTES > $BUNDLE_SIZE_LIMIT_BYTES ))
      then
        echo "Bundle size of $BUNDLE_SIZE_BYTES exceeds limit of $BUNDLE_SIZE_LIMIT_BYTES."
        echo "Please verify why this increased, and then update limit if size can't be optimized."
        echo "run 'pnpm package-bundle-analyzer' locally to identify bloat."
        exit 1
      else
        echo "Bundle size of $BUNDLE_SIZE_BYTES is within limit of $BUNDLE_SIZE_LIMIT_BYTES."
      fi
    shell: bash
