name: Deploy Preview

on:
  push:
    branches: [automated-socket-server-deployment]

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preview
    secrets: inherit
